import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/components/Theme/Theme";
import Navigation from "@/components/Navigation/Navigation";
import ClientLayout from "./ClientLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
